Test/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/$', login, {'template_name': 'index.html'}, name="login"),
    url(r'^logout/', logout_then_login, name="logout"),
    url(r'^reset/password_reset$', password_reset, {'template_name':'registration/password_reset_form.html', 
        'email_template_name':'registration/password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done$', password_reset_done, {'template_name':'registration/password_reset_done.html'}, 
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done$', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

apps/adopcion/urls.py
from __future__ import absolute_import
from django.conf.urls import url

from apps.adopcion.views import index, AdopcionList, AdopcionCreate, AdopcionUpdate, AdopcionDelete, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

urlpatterns = [
    url(r'^$', index, name="Index"),
    url(r'^nuevo$', AdopcionCreate.as_view(), name='adopcion_crear'),
    url(r'^listar$', AdopcionList.as_view(), name= "adopcion_listar"),
    url(r'^editar/(?P<pk>\d+)/$', AdopcionUpdate.as_view(), name="adopcion_editar"),
    url(r'^eliminar/(?P<pk>\d+)/$', AdopcionDelete.as_view(), name="adopcion_eliminar"),
    # Solicitudes
    url(r'^solicitud/listar$', SolicitudList.as_view(), name="solicitud_listar"),
    url(r'^solicitud/nueva$', SolicitudCreate.as_view(), name="solicitud_crear"),
    url(r'^solicitud/editar/(?P<pk>\d+)$', SolicitudUpdate.as_view(), name="solicitud_editar"),
    url(r'^solicitud/eliminar/(?P<pk>\d+)$', SolicitudDelete.as_view(), name="solicitud_eliminar"),
]

apps/adopcion/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Persona(models.Model):
    nombre    = models.CharField(max_length=20)
    apellidos = models.CharField(max_length=30)
    edad      = models.IntegerField()
    telefono  = models.CharField(max_length=12)
    domicilio = models.TextField()

    def __unicode__(self):
        return '{} {}'.format(self.nombre, self.apellidos)

class Solicitud(models.Model):
    persona = models.ForeignKey(Persona, null=True, blank=True)
    numero_mascotas = models.IntegerField()
    razones = models.TextField()
    

apps/adopcion/forms.py
from __future__ import absolute_import
from django import forms

from apps.adopcion.models import Persona, Solicitud

class AdopcionForm(forms.ModelForm):

    class Meta:
        model = Persona
        # Aqui se senalan los campos que nos traemos
        fields = [
            'nombre',
            'apellidos',
            'edad',
            'telefono',
            'domicilio',
        ]

        # Etiqueta de cada campo
        labels = {
            'nombre': 'Nombre',
            'apellidos': 'Apellidos',
            'edad': 'Edad',
            'telefono': 'Telefono',
            'domicilio': 'Domicilio',
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'apellidos': forms.TextInput(attrs={'class':'form-control'}),
            'edad': forms.NumberInput(attrs={'class':'form-control'}),
            'telefono': forms.TextInput(attrs={'class':'form-control'}),
            'domicilio': forms.TextInput(attrs={'class':'form-control'}),
        }


class SolicitudForm(forms.ModelForm):

    class Meta:
        model = Solicitud
        fields = [
            'numero_mascotas',
            'razones',
        ]

        labels = {
            'numero_mascotas': 'Numero de mascotas',
            'razones': 'Razones para adoptar',
        }

        widgets = {
            'numero_mascotas': forms.TextInput(attrs={'class':'form-control'}),
            'razones': forms.Textarea(attrs={'class':'form-control'}),
        }

apps/adopcion/views.py
from __future__ import absolute_import

from django.shortcuts import render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView # Vistas genericas
from django.core.urlresolvers import reverse_lazy

from apps.adopcion.models import Persona, Solicitud
from apps.adopcion.forms import AdopcionForm, SolicitudForm

# Create your views here.
def index(request):
    return HttpResponse("Hola Jefe. Estas en Index de Adopcion")

# Vistas para las Solicitudes
class SolicitudList(ListView):
    model = Solicitud
    template_name = 'adopcion/solicitud_list.html'
    context_object_name = 'lista_solicitudes'

class SolicitudCreate(CreateView):
    model = Solicitud
    form_class = SolicitudForm
    template_name = 'adopcion/solicitud_form.html'
    second_form_class = AdopcionForm
    success_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs):
        context = super(SolicitudCreate, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(self.request.GET)
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.second_form_class(request.POST)
        if form.is_valid() and form2.is_valid():
            solicitud = form.save(commit=False)
            solicitud.persona = form2.save()
            solicitud.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2))

class SolicitudUpdate(UpdateView):
    model = Solicitud
    second_model = Persona
    template_name = 'adopcion/solicitud_form.html'
    form_class = SolicitudForm
    second_form_class = AdopcionForm
    success_url = reverse_lazy('adopcion:solicitud_listar')

    def get_context_data(self, **kwargs):
        context = super(SolicitudUpdate, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk', 0)
        solicitud = self.model.objects.get(id=pk)
        persona   = self.second_model.objects.get(id=solicitud.persona_id)
        if 'form' not in context:
            context['form'] = self.form_class()
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=persona)
        context['id'] = pk
        return context
    
    def post(self, request, *args, **kwargs):
        self.object  = self.get_object
        id_solicitud = kwargs['pk']
        solicitud    = self.model.objects.get(id=id_solicitud)
        persona      = self.second_model.objects.get(id = solicitud.persona_id)
        form         = self.form_class(request.POST, instance = solicitud)
        form2        = self.second_form_class(request.POST, instance = persona)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return HttpResponseRedirect(self.get_success_url())

class SolicitudDelete(DeleteView):
    model = Solicitud
    template_name = 'adopcion/solicitud_delete.html'
    context_object_name = 'solicitud'
    success_url = reverse_lazy('adopcion:solicitud_listar')
    

# Vista basada en clase
# para el listado de los adoptantes
class AdopcionList(ListView):
    model = Persona
    template_name = 'adopcion/adopcion_list.html'
    queryset = Persona.objects.order_by('id')

class AdopcionCreate(CreateView):
    model = Persona
    form_class = AdopcionForm
    template_name = 'adopcion/adopcion_form.html'
    success_url = reverse_lazy('adopcion:adopcion_listar')

class AdopcionUpdate(UpdateView):
    model = Persona
    form_class = AdopcionForm
    template_name = 'adopcion/adopcion_form.html'
    success_url = reverse_lazy('adopcion:adopcion_listar')

class AdopcionDelete(DeleteView):
    model = Persona
    template_name = 'adopcion/adopcion_delete.html'
    context_object_name = 'adopcion' # Se envia el objeto con el nombre de adopcion
    success_url = reverse_lazy('adopcion:adopcion_listar')

templates/adopcion/adopcion_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de {{ adopcion.nombre }}?</h3>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'adopcion:adopcion_listar' %}">Cancelar</a>
</form>

{% endblock %}

templates/adopcion/adopcion_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>

{% endblock %}

templates/adopcion/adopcion_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <td><b>#</b></td>
            <td><b>Nombre</b></td>
            <td><b>Apellidos</b></td>
            <td><b>Edad</b></td>
            <td><b>Telefono</b></td>
            <td><b>Domicilio</b></td>
            <td><b>Acciones</b></td>
        </tr>
    </thead>
    <tbody>
        {% if object_list %}
            {% for adoptante in object_list %}
                <tr>
                    <td>{{ adoptante.id }}</td>
                    <td>{{ adoptante.nombre }}</td>
                    <td>{{ adoptante.apellidos }}</td>
                    <td>{{ adoptante.edad }}</td>
                    <td>{{ adoptante.telefono }}</td>
                    <td>{{ adoptante.domicilio }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'adopcion:adopcion_editar' adoptante.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'adopcion:adopcion_eliminar' adoptante.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h1>No hay registros de adoptantes.</h1>
        {% endif %}

    </tbody>
</table>

{% endblock %}

templates/adopcion/solicitud_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar la solicitud de {{ solicitud.persona.nombre }} {{ solicitud.persona.apellidos }}?</h3>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'adopcion:solicitud_listar' %}">Cancelar</a>
</form>

{% endblock %}

templates/adopcion/solicitud_form.html
{% extends 'base/base.html' %}

{% block content %}
<form method="post">
	{% csrf_token %}
	
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.nombre.name}}">{{form2.nombre.label}}</label>
				{{form2.nombre}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.nombre.apellidos}}">{{form2.apellidos.label}}</label>
				{{form2.apellidos}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.edad.name}}">{{form2.edad.label}}</label>
				{{form2.edad}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.email.name}}">{{form2.email.label}}</label>
				{{form2.email}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.telefono.name}}">{{form2.telefono.label}}</label>
				{{form2.telefono}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form2.domiclio.name}}">{{form2.domicilio.label}}</label>
				{{form2.domicilio}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.numero_mascotas.name}}">{{form.numero_mascotas.label}}</label>
				{{form.numero_mascotas}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.razones.name}}">{{form.razones.label}}</label>
				{{form.razones}}
			</div>
		</div>
	</div>
	<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-primary" type="submit">Guardar</button>
			</div>
		</div>
</form>
{% endblock %}

templates/adopcion/solicitud_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <td><b># Solicitud</b></td>
            <td><b>Adoptante</b></td>
            <td><b>No. Mascotas</b></td>
            <td><b>Razones</b></td>
            <td><b>Acciones</b></td>
        </tr>
    </thead>
    <tbody>
        {% if lista_solicitudes %}
            {% for solicitud in lista_solicitudes %}
                <tr>
                    <td>{{ solicitud.id }}</td>
                    <td>{{ solicitud.persona.nombre}} {{ solicitud.persona.apellidos }}</td>
                    <td>{{ solicitud.numero_mascotas }}</td>
                    <td>{{ solicitud.razones }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'adopcion:solicitud_editar' solicitud.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h1>No hay solicitudes para adopar perros.</h1>
        {% endif %}

    </tbody>
</table>

{% endblock %}