Test/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/$', login, {'template_name': 'index.html'}, name="login"),
    url(r'^logout/', logout_then_login, name="logout"),
    url(r'^reset/password_reset$', password_reset, {'template_name':'registration/password_reset_form.html', 
        'email_template_name':'registration/password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done$', password_reset_done, {'template_name':'registration/password_reset_done.html'}, 
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done$', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

apps/adopcion/urls.py
from __future__ import absolute_import
from django.conf.urls import url

from apps.adopcion.views import index, AdopcionList, AdopcionCreate, AdopcionUpdate, AdopcionDelete, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

urlpatterns = [
    url(r'^$', index, name="Index"),
    url(r'^nuevo$', AdopcionCreate.as_view(), name='adopcion_crear'),
    url(r'^listar$', AdopcionList.as_view(), name= "adopcion_listar"),
    url(r'^editar/(?P<pk>\d+)/$', AdopcionUpdate.as_view(), name="adopcion_editar"),
    url(r'^eliminar/(?P<pk>\d+)/$', AdopcionDelete.as_view(), name="adopcion_eliminar"),
    # Solicitudes
    url(r'^solicitud/listar$', SolicitudList.as_view(), name="solicitud_listar"),
    url(r'^solicitud/nueva$', SolicitudCreate.as_view(), name="solicitud_crear"),
    url(r'^solicitud/editar/(?P<pk>\d+)$', SolicitudUpdate.as_view(), name="solicitud_editar"),
    url(r'^solicitud/eliminar/(?P<pk>\d+)$', SolicitudDelete.as_view(), name="solicitud_eliminar"),
]

apps/mascota/urls.py
from __future__ import absolute_import

from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^nuevo$', login_required(mascota_view), name="mascota_crear"),
    url(r'^listar$', login_required(mascota_list), name="mascota_listar"),
    url(r'^editar/(?P<id_mascota>\d+)$', login_required(mascota_edit), name="mascota_editar"),
    url(r'^eliminar/(?P<id_mascota>\d+)$', login_required(mascota_delete), name="mascota_eliminar"),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Refugio Facilito {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="{% url 'mascota:index' %}">Home</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas <span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'mascota:mascota_crear' %}">Registrar</a></li>
				                        	<li><a href="{% url 'mascota:mascota_listar' %}">Listar</a></li>
				                        </ul>
		                      		</li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Adopciones<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href="{% url 'adopcion:solicitud_crear' %}">Solicitar</a></li>
				                          	<li><a href="{% url 'adopcion:solicitud_listar' %}">Listar Solicitudes</a></li>
			                        	</ul>
			                        </li>
		                    	</ul>
		                    	<ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown"><a href="http://codigofacilito.com" onclick="pageTracker._link(this.href); return false;">Código Facilito</a>
		                        	</li>
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="{% url 'logout' %}">Salir</a></li>
		                        		</ul>
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>    

	{% endblock %}


	{% block content %}
	<h4>	Bienvenido al módulo de adopción de mascotas.		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>

templates/base/header.html
<header> Hola </header>