Test/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/$', login, {'template_name': 'index.html'}, name="login"),
    url(r'^logout/', logout_then_login, name="logout"),
    url(r'^reset/password_reset$', password_reset, {'template_name':'registration/password_reset_form.html', 
        'email_template_name':'registration/password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done$', password_reset_done, {'template_name':'registration/password_reset_done.html'}, 
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done$', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

apps/mascota/urls.py
from __future__ import absolute_import

from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^nuevo$', login_required(mascota_view), name="mascota_crear"),
    url(r'^listar$', login_required(mascota_list), name="mascota_listar"),
    url(r'^editar/(?P<id_mascota>\d+)$', login_required(mascota_edit), name="mascota_editar"),
    url(r'^eliminar/(?P<id_mascota>\d+)$', login_required(mascota_delete), name="mascota_eliminar"),
]

apps/mascota/models.py
from __future__ import unicode_literals, absolute_import

from django.db import models
from apps.adopcion.models import Persona

# Create your models here.
class Vacuna(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __unicode__(self):
        return '{}'.format(self.nombre)

class Mascota(models.Model):
    nombre = models.CharField(max_length=50)
    sexo   = models.CharField(max_length=10)
    edad   = models.IntegerField()
    fecha_rescate = models.DateField()
    persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
    vacuna = models.ManyToManyField(Vacuna, blank=True)

    def __unicode__(self):
        return '{} - {}'.format(self.nombre, self.sexo)

apps/mascota/forms.py
from __future__ import absolute_import
from django import forms

from apps.mascota.models import Mascota
# Obtenemos el formulario de acuerdo al modelo que
# seleccionamos
class MascotaForm(forms.ModelForm):

    class Meta:
        model = Mascota
        # Aqui se senalan los campos que nos traemos
        fields = [
            'nombre',
            'sexo',
            'edad',
            'fecha_rescate',
            'persona',
            'vacuna',
        ]

        # Aqui senalamos la etiqueta de cada campo 
        # que nos vamos a traer
        labels = {
            'nombre': 'Nombre',
            'sexo': 'Sexo',
            'edad': 'Edad Aprox.',
            'fecha_rescate': 'Fecha de Rescate',
            'persona': 'Adoptante',
            'vacuna': 'Vacunas',
        }

        # Son los que se van a pintar a forma de etiquetas
        # en html
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'sexo': forms.TextInput(attrs={'class':'form-control'}),
            'edad': forms.TextInput(attrs={'class':'form-control'}),
            'fecha_rescate': forms.DateInput(format=('%d-%m-%Y'), attrs={'class':'form-control'}),
            'persona': forms.Select(attrs={'class':'form-control'}),
            'vacuna': forms.CheckboxSelectMultiple(),
        }

apps/mascota/views.py
from __future__ import absolute_import
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView # Para las vistas genericas

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota

# Vistas Basadas en funciones
def index(request):
    return render(request, 'mascota/index.html')

def mascota_view(request):
    if request.method == 'POST':
        form = MascotaForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mascota:index')
    else:
        form = MascotaForm()
    
    return render(request, 'mascota/mascota_form.html', {'form': form})

def mascota_list(request):
    mascota = Mascota.objects.all().order_by('id')
    context = {
        'mascotas': mascota,
    }
    return render(request, 'mascota/mascota_list.html', context)

def mascota_edit(request, id_mascota):
    mascota = Mascota.objects.get(id=id_mascota)
    if request.method == 'GET':
        form = MascotaForm(instance=mascota)
    else:
        form = MascotaForm(request.POST, instance=mascota)
        if form.is_valid():
            form.save()
        return redirect('mascota:mascota_listar')
    
    return render (request, 'mascota/mascota_form.html', {'form':form})

def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect('mascota:mascota_listar')
	return render(request, 'mascota/mascota_delete.html', {'mascota':mascota})


# Vistas Basadas en Clases
# class MascotaList(ListView):
#     model = Mascota
#     template_name = 'mascota/mascota_list.html'

templates/mascota/index.html
{% extends 'base/base.html' %}

templates/mascota/mascota_delete.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de {{ mascota.nombre }}?</h3>
    <button class="btn btn-danger" type="submit">Si, eliminar</button>
    <a class="btn btn-default" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
</form>

{% endblock %}

templates/mascota/mascota_form.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>

{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
    <thead>
        <tr>
            <td><b>#</b></td>
            <td><b>Nombre</b></td>
            <td><b>Sexo</b></td>
            <td><b>Edad</b></td>
            <td><b>Fecha de Rescate</b></td>
            <td><b>Adoptante</b></td>
            <td><b>Acciones</b></td>
        </tr>
    </thead>
    <tbody>
        {% if mascotas %}
            {% for mascota in mascotas %}
                <tr>
                    <td>{{ mascota.id }}</td>
                    <td>{{ mascota.nombre }}</td>
                    <td>{{ mascota.sexo }}</td>
                    <td>{{ mascota.edad }}</td>
                    <td>{{ mascota.fecha_rescate }}</td>
                    <td>{{ mascota.persona }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'mascota:mascota_editar' mascota.id %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'mascota:mascota_eliminar' mascota.id %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <h1>No hay registros de mascotas.</h1>
        {% endif %}

    </tbody>
</table>

{% endblock %}